In [200]:
## importing libraries

In [202]:
import numpy as np

import sklearn

import pandas as pd
import matplotlib.pyplot as plt

In [204]:
## importing THE data file

In [205]:
dataset = pd.read_csv('Iris.csv')

x = dataset.iloc[:, :-1].values

y = dataset.iloc[:, -1].values

missing_data = dataset.isnull().sum()

In [208]:
## SPLITTING THE DATASET INTO TRAINING SET AND TEST SET

In [209]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

print(x_train)

[[1.38e+02 6.40e+00 3.10e+00 5.50e+00 1.80e+00]
 [8.50e+01 5.40e+00 3.00e+00 4.50e+00 1.50e+00]
 [2.80e+01 5.20e+00 3.50e+00 1.50e+00 2.00e-01]
 [1.28e+02 6.10e+00 3.00e+00 4.90e+00 1.80e+00]
 [1.33e+02 6.40e+00 2.80e+00 5.60e+00 2.20e+00]
 [6.00e+01 5.20e+00 2.70e+00 3.90e+00 1.40e+00]
 [1.90e+01 5.70e+00 3.80e+00 1.70e+00 3.00e-01]
 [8.40e+01 6.00e+00 2.70e+00 5.10e+00 1.60e+00]
 [6.20e+01 5.90e+00 3.00e+00 4.20e+00 1.50e+00]
 [9.30e+01 5.80e+00 2.60e+00 4.00e+00 1.20e+00]
 [1.13e+02 6.80e+00 3.00e+00 5.50e+00 2.10e+00]
 [3.00e+00 4.70e+00 3.20e+00 1.30e+00 2.00e-01]
 [1.42e+02 6.90e+00 3.10e+00 5.10e+00 2.30e+00]
 [4.40e+01 5.00e+00 3.50e+00 1.60e+00 6.00e-01]
 [1.10e+01 5.40e+00 3.70e+00 1.50e+00 2.00e-01]
 [6.10e+01 5.00e+00 2.00e+00 3.50e+00 1.00e+00]
 [1.17e+02 6.50e+00 3.00e+00 5.50e+00 1.80e+00]
 [1.45e+02 6.70e+00 3.30e+00 5.70e+00 2.50e+00]
 [1.20e+02 6.00e+00 2.20e+00 5.00e+00 1.50e+00]
 [1.09e+02 6.70e+00 2.50e+00 5.80e+00 1.80e+00]
 [7.00e+01 5.60e+00 2.50e+00 3.90e+00 1.

In [210]:
## FEATURE SCALING

In [212]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)

x_test = sc.transform(x_test)
print(x_train)

[[ 1.34636602  0.61303014  0.10850105  0.94751783  0.73603967]
 [ 0.16184701 -0.56776627 -0.12400121  0.38491447  0.34808318]
 [-1.11206965 -0.80392556  1.03851009 -1.30289562 -1.3330616 ]
 [ 1.12287187  0.25879121 -0.12400121  0.60995581  0.73603967]
 [ 1.23461894  0.61303014 -0.58900572  1.00377816  1.25331499]
 [-0.39688836 -0.80392556 -0.82150798  0.04735245  0.21876435]
 [-1.31321439 -0.21352735  1.73601687 -1.19037495 -1.20374277]
 [ 0.1394976   0.14071157 -0.82150798  0.72247648  0.47740201]
 [-0.35218953  0.02263193 -0.12400121  0.21613346  0.34808318]
 [ 0.34064234 -0.09544771 -1.05401024  0.10361279 -0.03987331]
 [ 0.78763064  1.0853487  -0.12400121  0.94751783  1.12399616]
 [-1.67080503 -1.39432376  0.34100331 -1.41541629 -1.3330616 ]
 [ 1.43576368  1.20342834  0.10850105  0.72247648  1.38263382]
 [-0.75447901 -1.04008484  1.03851009 -1.24663528 -0.81578628]
 [-1.49200971 -0.56776627  1.50351461 -1.30289562 -1.3330616 ]
 [-0.37453895 -1.04008484 -2.4490238  -0.1776889  -0.29

In [215]:
 ## TRAINING THE DECISION TREE MODEL ONTHE TRAINING SET

In [216]:
from sklearn.tree import DecisionTreeClassifier

classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)

classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [218]:
## predicting the result

In [219]:
y_pred = classifier.predict(x_test)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-versicolor' 'Iris-versicolor']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-virginica' 'Iris-virginica']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-setosa' 'Iris-setosa']
 ['Iris-versicolor' 'Iris-versicolor']

In [222]:
 ## MAKING THE CONFUSION MATRIX

In [223]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)

print(cm)

accuracy_score(y_test, y_pred)

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]


0.9666666666666667